### ISSUE TITLE
Getting error while "make up" in MAC

### ISSUE THREAD

**Issue by vizmur** [splunk/splunk-app-examples#48]
Getting below error while making on MAC M2

Installing collected packages: splunk-sdk, urllib3, python-dotenv, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2023.7.22 charset-normalizer-3.2.0 idna-3.4 python-dotenv-1.0.0 requests-2.31.0 splunk-sdk-1.7.4 urllib3-2.0.5
[+] Running 0/1
 ⠧ splunk Pulling                                                                                                                 3.7s 
no matching manifest for linux/arm64/v8 in the manifest list entries
make: *** [up] Error 18

**Comment by r48patel** [comment]
As a temporary solution, I ended up adding `platform: linux/x86_64` in the `docker-compose.yml`

```
version: '3.6'

services:
    splunk:
        platform: linux/x86_64
        image: "splunk/splunk:latest"
...
```

Hope that helps.
